apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: control-plane
spec:
  version: v1.25-latest
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 1024Mi

