apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    resourceNames:
      - "${PROJECT_NAME}-0-0"
    verbs: ["create"]
