apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-rolebinding
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exec-role
  apiGroup: rbac.authorization.k8s.io

