kind: Service
apiVersion: v1
metadata:
  name: vllm-30801
spec:
  type: ClusterIP
  selector:
    app: vllm-30801
  ports:
  - protocol: TCP
    port: 30801
    targetPort: 30801
---
kind: Service
apiVersion: v1
metadata:
  name: vllm-30802
spec:
  type: ClusterIP
  selector:
    app: vllm-30802
  ports:
  - protocol: TCP
    port: 30802
    targetPort: 30802
---
kind: Service
apiVersion: v1
metadata:
  name: vllm-30803
spec:
  type: ClusterIP
  selector:
    app: vllm-30803
  ports:
  - protocol: TCP
    port: 30803
    targetPort: 30803
