apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-picker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint-picker
  template:
    metadata:
      labels:
        app: endpoint-picker
    spec:
      serviceAccountName: endpoint-picker
      containers:
        - name: endpoint-picker
          image: quay.io/vllm-d/gateway-api-inference-extension/epp:0.0.1
          args:
            - "--config-file"
            - "/etc/endpoint-picker/config.yaml"
          ports:
            - name: grpc
              containerPort: 9080
              protocol: TCP
          volumeMounts:
            - name: endpoint-picker-config
              mountPath: /etc/endpoint-picker
      volumes:
        - name: endpoint-picker-config
          configMap:
            name: endpoint-picker-config
