apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-picker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoint-picker
rules:
  - apiGroups:
    - ""
    resources:
    - "pods"
    verbs:
    - "get"
    - "list"
    - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-picker-binding
subjects:
  - kind: ServiceAccount
    name: endpoint-picker
roleRef:
  kind: Role
  name: endpoint-picker
  apiGroup: rbac.authorization.k8s.io

