# ------------------------------------------------------------------------------
# Kubernetes In Docker (KIND) Environment
#
# This will deploy the full development stack on a KIND cluster:
#
#  * Istio Control Plane
#  * VLLM Simulator
#  * Inference Gateway
#
# **Note**: The Sail Operator must be deployed first.
#
# This will expose the VLLM simulator via an HTTPRoute. You can access the
# Gateway with a port-forward:
#
#   $ kubectl port-forward service/inference-gateway-istio 8080:80
#
# And the requests can be made:
#
#   $  curl -v -w '\n' -X POST -H 'Content-Type: application/json' \
#     -d '{"model":"model1","messages":[{"role":"user","content":"Hello!"}]}' \
#     http://localhost:8080/v1/chat/completions
#
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../components/istio-control-plane/
- ../../components/vllm-sim/
- ../../components/inference-gateway/
- httproutes.yaml
