apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'vllm'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Keep only pods with app=vllm-llama3-8b-instruct
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: vllm-llama3-8b-instruct

          # Set __address__ to pod_ip:8000
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:8000

          # Optional: preserve useful pod metadata as Prometheus labels
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

        metrics_path: /metrics
        scheme: http